#!/usr/bin/env python3

URL = 'https://support.google.com/chromeosflex/answer/11513094'

from typing import List
import bs4
import requests
import logging

# Get the list of models from the Google support page
# Note: This was completely auto-generated by Copilot 🤯
def get_models_list() -> List[str]:
    response = requests.get(URL)
    response.raise_for_status()
    soup = bs4.BeautifulSoup(response.text, 'html.parser')
    models = soup.select('table tr td:nth-of-type(1)')
    return [model.text for model in models]

def write_to_file(models: List[str]) -> None:
    models.sort()
    with open('models.txt', 'w') as f:
        f.write("\n".join(models))

def main():
    models = get_models_list()
    write_to_file(models)

if __name__ == '__main__':
    main()
