name: Generate models list
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.5
      - name: Setup Python
        uses: actions/setup-python@v4.8.0
        with:
          python-version: "3.11"
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: Install dependencies
        # if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --ignore-pipfile --deploy
      - name: Generate
        run: |
          pipenv run ./main.py
      - uses: EndBug/add-and-commit@v9.1.4
        if: startsWith(github.ref, 'refs/heads/renovate/') != true
        with:
          default_author: github_actions
        
